# -*- coding: utf-8 -*-
"""superior.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10VXl35LuNrVo8dW8xoJP2nyuFoE7Gx78
"""

def fibo(n,a=0,b=1,c=0):
  if(n==1):
      return a
  else:
      return a + fibo(n-1,b,c,a+b)
v = 6
while(v > 0):
    print(fibo(v))
    v=v-1

print(fibo(2))