# -*- coding: utf-8 -*-
"""FibonacciPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1We38tg3GdKFDi1Nj_7HCtLcI-SCTSuXp
"""

#Forma iterativa
def fibo():
  n=int(input())
  a=0
  b=1
  for i in range(n):
    print(a) 
    c=a+b
    a=b
    b=c

#Forma Recursiva
def fibrecu(n):
  if n<2:
    return n
  return fibrecu(n-1)+fibrecu(n-2)

fibo()

n=int(input())
for n in range(0, n):
  print(fibrecu(n))